<?php

namespace common\models;

use Yii;

/**
 * This is the model class for table "blog".
 *
 * @property integer $id
 * @property string $title
 * @property string $content
 * @property integer $views
 * @property integer $is_delete
 * @property string $created_at
 * @property string $updated_at
 * @property string $file
 * @property string $file2
 */
class Blog extends \yii\db\ActiveRecord
{
    public $category;
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'blog';
    }

    // 绑定事件
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->on(self::EVENT_BEFORE_INSERT,[$this,'onBeforeInsert']);
        $this->on(self::EVENT_AFTER_INSERT,[$this,'onAfterInsert']);
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['content'], 'required'],
            [['id', 'views', 'is_delete'], 'integer'],
            [['content'], 'string'],
            [['created_at', 'updated_at'], 'safe'],
            [['title'], 'string', 'max' => 100],
            [['title', 'content', 'category'], 'required'],
            [['file', 'file2'], 'required'],
            [['file', 'file2'], 'safe'],
            [['file'], 'string', 'max' => 255],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'title' => '标题',
            'content' => '文章内容',
            'views' => '点击量',
            'is_delete' => '是否删除',
            'created_at' => '添加时间',
            'updated_at' => '更新时间',
            'file' => '单图',
            'file2' => '多图',
        ];
    }

    // 新增时间和修改时间
    public function beforeSave($insert)
    {
        if(parent::beforeSave($insert)){
            if ($insert){
                $this->created_at = time();
                $this->updated_at = time();
            }else{
                $this->updated_at = time();
            }
            return true;
        }else{
            return false;
        }
    }

    public function onBeforeInsert($event)
    {
        yii::info('This is beforeInsert event.');
    }

    public function onAfterInsert($event)
    {
        yii::info('This is afterInsert event.');
    }
}
