<?php
/**
 * Created by PhpStorm.
 * User: liumaxiao
 * Date: 2017/9/4
 * Time: 9:45
 */
namespace backend\components;

use Yii;

class MyBehavior extends \yii\base\ActionFilter
{
    public function beforeAction($action)
    {
        var_dump(111);
        return true;
//        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    public function isGuest()
    {
        return Yii::$app->user->isGuest;
    }
}